# Generated by Django 4.2.29 on 2026-03-13 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='bi-tag', max_length=60)),
                ('category_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('sparepart', 'Spare Part')], default='vehicle', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('variant', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('condition', models.CharField(choices=[('new', 'Brand New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'For Parts / Not Running')], default='good', max_length=20)),
                ('description', models.TextField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('cng', 'CNG'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('lpg', 'LPG'), ('na', 'N/A')], default='petrol', max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('semi_auto', 'Semi-Automatic'), ('na', 'N/A')], default='manual', max_length=20)),
                ('km_driven', models.PositiveIntegerField(default=0, help_text='Kilometers driven')),
                ('engine_cc', models.PositiveIntegerField(blank=True, help_text='Engine capacity in CC', null=True)),
                ('num_owners', models.CharField(choices=[('1', '1st Owner'), ('2', '2nd Owner'), ('3', '3rd Owner'), ('4', '4th Owner or more')], default='1', max_length=5)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('rto_state', models.CharField(blank=True, help_text='Registration state e.g. MH, TN', max_length=100)),
                ('registration_year', models.PositiveIntegerField(blank=True, null=True)),
                ('insurance', models.CharField(choices=[('comprehensive', 'Comprehensive'), ('third_party', 'Third Party'), ('expired', 'Expired'), ('none', 'None')], default='third_party', max_length=20)),
                ('insurance_valid_until', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_negotiable', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sold', 'Sold')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_listings', to='listings.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SparePartListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('part_name', models.CharField(help_text='e.g. Brake Pad, Alternator, Headlight', max_length=150)),
                ('part_number', models.CharField(blank=True, help_text='OEM / manufacturer part number', max_length=100)),
                ('part_type', models.CharField(choices=[('engine', 'Engine Parts'), ('body', 'Body Parts'), ('electrical', 'Electrical & Electronics'), ('suspension', 'Suspension & Steering'), ('brakes', 'Brakes'), ('transmission', 'Transmission & Gearbox'), ('exhaust', 'Exhaust System'), ('tyres', 'Tyres & Wheels'), ('interior', 'Interior & Accessories'), ('lights', 'Lights & Indicators'), ('battery', 'Battery & Charging'), ('filters', 'Filters & Fluids'), ('other', 'Other')], default='engine', max_length=30)),
                ('condition', models.CharField(choices=[('new', 'Brand New'), ('oem', 'OEM / Original'), ('used_good', 'Used - Good Condition'), ('used_fair', 'Used - Fair Condition'), ('refurbished', 'Refurbished')], default='used_good', max_length=20)),
                ('description', models.TextField()),
                ('brand', models.CharField(blank=True, help_text='Part brand / manufacturer', max_length=100)),
                ('compatible_vehicle_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike / Scooter'), ('truck', 'Truck / Commercial'), ('tractor', 'Tractor / Farm'), ('universal', 'Universal / All Vehicles')], default='car', max_length=20)),
                ('compatible_brand', models.CharField(blank=True, help_text='e.g. Maruti, Honda', max_length=100)),
                ('compatible_model', models.CharField(blank=True, help_text='e.g. Swift, City', max_length=100)),
                ('compatible_year_from', models.PositiveIntegerField(blank=True, null=True)),
                ('compatible_year_to', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_negotiable', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sold', 'Sold')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sparepart_listings', to='listings.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sparepart_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='listings/%Y/%m/')),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('spare_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.sparepartlisting')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.vehiclelisting')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
    ]
